


server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test

logging:
  level:
    root: info
    com:
      zzm:
        dao: trace
mybatis:
  mapper-locations: classpath*:/mapper/*.xml